# Dockerfile pour un microservice ASP.NET
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copie le fichier .csproj et restaure les dépendances
COPY ["Identity/IdentityApi.csproj", "Identity/"]
RUN dotnet restore "Identity/IdentityApi.csproj"

# Copie tout le projet et build
COPY . .
WORKDIR "/src/Identity"
RUN dotnet build "IdentityApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "IdentityApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IdentityApi.dll"]
